FROM node:13-alpine

RUN \
apk update && \
apk upgrade && \
apk add --upgrade dumb-init && \
apk add git

WORKDIR /cgv-api-customer

RUN chown -R node /cgv-api-customer

USER node

COPY --chown=node:node ["package.json", "package-lock.json", "./"]

RUN npm ci

USER root

RUN npm i -g prisma

USER node

CMD ["dumb-init", "npm", "run", "start:api:dev"]